#include <avr/io.h>
#include <util/delay.h>

#include "include/i2c.h"
#include "include/mpu60x0.h"
#include "include/gyro.h"

void
gyro_init()
{
  _delay_ms(150);

  /* Upon power up, the MPU-60X0 clock source defaults to the internal
   * oscillator. However, it is highly recommended that the device be
   * configured to use one of the gyroscopes (or an external clock
   * source) as the clock reference for improved stability.
   *
   * PLL with X axis gyroscope reference */
  i2c_set_register(PWR_MGMT_1, 1);

  /* The DLPF (Digital Low Pass Filter) is configured by DLPF_CFG. The
   * accelerometer and gyroscope are filtered according to the value
   * of DLPF_CFG
   *
   * Default: DLPF_CFG = 0 */
  i2c_set_register(CONFIG, 0);

  /* This register specifies the divider from the gyroscope output
   * rate used to generate the Sample Rate for the MPU-60X0.  The
   * sensor register output, FIFO output, DMP sampling and Motion
   * detection are all based on the Sample Rate. The Sample Rate is
   * generated by dividing the gyroscope output rate by SMPLRT_DIV:
   * Sample Rate = Gyroscope Output Rate / (1 + SMPLRT_DIV)
   * where Gyroscope Output Rate = 8kHz when the DLPF is disabled
   * (DLPF_CFG = 0 or 7), and 1kHz when the DLPF is enabled (see
   * Register 26).
   *
   * Note: The accelerometer output rate is 1kHz. This
   * means that for a Sample Rate greater than 1kHz, the same
   * accelerometer sample may be output to the FIFO, DMP, and sensor
   * registers more than once.
   *
   * DLPF is disabled. Sample Rate is 1kHz */
  i2c_set_register(SMPLRT_DIV, 7);

  /* Selects the full scale range of the gyroscope outputs
   *
   * ± 2000 °/s */ 
  i2c_set_register(GYRO_CONFIG, 0x18);

  /* This register enables interrupt generation by interrupt sources.
   *
   * When set to 1, this bit enables the Data Ready interrupt, which
   * occurs each time a write operation to all of the sensor registers
   * has been completed. */
  i2c_set_register(INT_ENABLE, 1);
}
